import type { Action, Level } from "./types";

export const PROVIDER_DOMAINS: Record<string, string> = {
  aws:             "aws.amazon.com",
  google:          "google.com",
  azure:           "microsoft.com",
  comptia:         "comptia.org",
  isc2:            "isc2.org",
  tcm:             "tcm-sec.com",
  tryhackme:       "tryhackme.com",
  htb:             "hackthebox.com",
  acloudguru:      "acloudguru.com",
  cloudguru:       "acloudguru.com",
  rhino:           "rhinosecuritylabs.com",
  github:          "github.com",
  youtube:         "www.youtube.com",
  sans:            "sans.org",
  offsec:          "offsec.com",
  pwnedlabs:       "pwnedlabs.io",
  hacktricks:      "cloud.hacktricks.xyz",
  skillbuilder:    "skillbuilder.aws",
  flaws:           "flaws.cloud",
  checkov:         "checkov.io",
  wiz:             "wiz.io",
  prowler:         "prowler.com",
  sysdig:          "sysdig.com",
  crowdstrike:     "crowdstrike.com",
};

export const LEVELS: Level[] = [
  {
    num: "00",
    label: "Cloud Foundations",
    subtitle: "Zero to Cloud Literate",
    color: "#ada3c1",
    glow: "rgba(173,163,193,0.2)",
    border: "rgba(173,163,193,0.25)",
    quote:
      "You cannot secure a cloud environment you don't understand. Start with how it works — security comes next.",
    time: "0–6 months",
    tools: ["AWS Console", "AWS CLI", "VirtualBox", "Linux Terminal"],
    skills: [
      "Cloud concepts — IaaS, PaaS, SaaS, shared responsibility model",
      "Core AWS services — EC2, S3, IAM, VPC, RDS",
      "Networking fundamentals — subnets, routing, security groups",
      "IAM basics — users, groups, roles, policies, least privilege",
    ],
    certs: [
      { label: "AWS Certified Cloud Practitioner (CLF-C02)", link: "https://aws.amazon.com/certification/certified-cloud-practitioner/", provider: "aws" },
      { label: "Google Associate Cloud Engineer", link: "https://cloud.google.com/learn/certification/cloud-engineer", provider: "google" },
    ],
    labs: [
      { label: "AWS Skill Builder — Cloud Practitioner Essentials", link: "https://skillbuilder.aws/", provider: "skillbuilder" },
      { label: "TryHackMe · AWS Fundamentals room", link: "https://tryhackme.com/room/awsfundamentals", provider: "tryhackme" },
      { label: "flaws.cloud — Learn AWS through offense", link: "http://flaws.cloud/", provider: "flaws" },
      { label: "AWS Free Tier — hands-on with real services", link: "https://aws.amazon.com/free/", provider: "aws" },
      { label: "A Cloud Guru — AWS Cloud Practitioner course", link: "https://acloudguru.com/course/aws-certified-cloud-practitioner", provider: "acloudguru" },
    ],
  },
  {
    num: "01",
    label: "Cloud Security Associate",
    subtitle: "Identity, Visibility & Hardening",
    color: "#a78bfa",
    glow: "rgba(167,139,250,0.2)",
    border: "rgba(167,139,250,0.25)",
    quote:
      "GuardDuty fired at 2am. Can you tell me what happened, who touched what, and whether it matters? That's this level.",
    time: "6 months – 2 years",
    tools: ["CloudTrail", "Security Hub", "GuardDuty", "AWS Config", "IAM Access Analyzer"],
    skills: [
      "IAM policy analysis — reading JSON policies, spotting over-privilege",
      "CloudTrail + CloudWatch — event correlation and alerting",
      "S3 security — block public access, bucket policies, ACLs, encryption",
      "Security Hub + Config Rules — posture management basics",
    ],
    certs: [
      { label: "AWS Certified Solutions Architect – Associate (SAA-C03)", link: "https://aws.amazon.com/certification/certified-solutions-architect-associate/", provider: "aws" },
      { label: "CompTIA Security+ SY0-701", link: "https://www.comptia.org/certifications/security", provider: "comptia" },
    ],
    labs: [
      { label: "flaws.cloud (Levels 1–6 — real AWS misconfigs)", link: "http://flaws.cloud/", provider: "flaws" },
      { label: "TryHackMe · AWS IAM room", link: "https://tryhackme.com/room/awsiam", provider: "tryhackme" },
      { label: "PwnedLabs — Cloud Security Labs", link: "https://pwnedlabs.io/", provider: "pwnedlabs" },
      { label: "AWS Skill Builder — Security Learning Plan", link: "https://skillbuilder.aws/", provider: "skillbuilder" },
      { label: "A Cloud Guru — AWS Security specialty prep", link: "https://acloudguru.com/", provider: "acloudguru" },
    ],
  },
  {
    num: "02",
    label: "Cloud Security Engineer",
    subtitle: "Automation, IaC & Posture at Scale",
    color: "#a855f7",
    glow: "rgba(168,85,247,0.2)",
    border: "rgba(168,85,247,0.25)",
    quote:
      "Manual reviews don't scale. If you can't codify it as policy, you can't defend 500 resources. Automate everything.",
    time: "2–5 years",
    tools: ["Terraform", "Checkov", "Prowler", "Falco", "AWS WAF", "Inspector"],
    skills: [
      "IaC security — scanning Terraform/CloudFormation with Checkov and tfsec",
      "CSPM — continuous posture assessment with Prowler and ScoutSuite",
      "Container security — ECS/EKS hardening, image scanning, Falco runtime policies",
      "Incident response in cloud — isolate, preserve, investigate using CloudTrail",
    ],
    certs: [
      { label: "AWS Certified Security – Specialty (SCS-C02)", link: "https://aws.amazon.com/certification/certified-security-specialty/", provider: "aws" },
      { label: "CCSP — Certified Cloud Security Professional (ISC²)", link: "https://www.isc2.org/certifications/ccsp", provider: "isc2" },
    ],
    labs: [
      { label: "CloudGoat by Rhino Security Labs (IaC attack scenarios)", link: "https://github.com/RhinoSecurityLabs/cloudgoat", provider: "rhino" },
      { label: "PwnedLabs — Cloud Security Engineering labs", link: "https://pwnedlabs.io/", provider: "pwnedlabs" },
      { label: "Prowler Open Source (run against your own account)", link: "https://github.com/prowler-cloud/prowler", provider: "prowler" },
      { label: "HackTricks Cloud — AWS attack techniques reference", link: "https://cloud.hacktricks.xyz/", provider: "hacktricks" },
      { label: "SANS SEC510 — Public Cloud Security", link: "https://www.sans.org/cyber-security-courses/public-cloud-security-aws-azure-gcp/", provider: "sans" },
    ],
  },
  {
    num: "03",
    label: "Cloud Penetration Tester",
    subtitle: "Offensive Cloud & Privilege Escalation",
    color: "#7c3aed",
    glow: "rgba(124,58,237,0.2)",
    border: "rgba(124,58,237,0.25)",
    quote:
      "You stop asking 'are we secure?' and start asking 'how far can I go from this S3 bucket?' One compromised IAM key becomes domain admin if you know the path.",
    time: "4–8 years",
    tools: ["Pacu", "CloudFox", "enumerate-iam", "Burp Suite", "Metasploit", "SSRF payloads"],
    skills: [
      "AWS privilege escalation chains — iam:PassRole, sts:AssumeRole, lambda:CreateFunction",
      "SSRF → metadata service abuse (IMDSv1 exploitation)",
      "Assumed role pivoting and cross-account attacks",
      "Multi-cloud attack paths — Azure AD, GCP service accounts",
    ],
    certs: [
      { label: "AWS Certified Security – Specialty (SCS-C02)", link: "https://aws.amazon.com/certification/certified-security-specialty/", provider: "aws" },
      { label: "TCM Security — Cloud Security Practitioner", link: "https://certifications.tcm-sec.com/", provider: "tcm" },
    ],
    labs: [
      { label: "flaws2.cloud — Offensive AWS path", link: "https://flaws2.cloud/", provider: "flaws" },
      { label: "CloudGoat — All advanced scenarios", link: "https://github.com/RhinoSecurityLabs/cloudgoat", provider: "rhino" },
      { label: "Pacu — AWS Exploitation Framework", link: "https://github.com/RhinoSecurityLabs/pacu", provider: "rhino" },
      { label: "CloudFox by BishopFox", link: "https://github.com/BishopFox/cloudfox", provider: "github" },
      { label: "HackTricks Cloud — Full attack reference", link: "https://cloud.hacktricks.xyz/", provider: "hacktricks" },
    ],
  },
  {
    num: "04",
    label: "Cloud Security Architect",
    subtitle: "Zero Trust, CNAPP & Enterprise Programs",
    color: "#6d28d9",
    glow: "rgba(109,40,217,0.2)",
    border: "rgba(109,40,217,0.25)",
    quote:
      "Security architecture is product design. You're not patching servers — you're designing systems where the breach radius is always bounded.",
    time: "8+ years",
    tools: ["Wiz", "Prisma Cloud", "AWS Organizations", "SCP (Service Control Policies)", "CNAPP platforms"],
    skills: [
      "Zero Trust cloud architecture — continuous verification, microsegmentation",
      "CNAPP strategy — integrating CSPM, CWPP, CIEM, and DSPM",
      "Multi-account governance with AWS Organizations and SCPs",
      "Threat modeling for cloud-native applications and supply chains",
    ],
    certs: [
      { label: "CISSP — Certified Information Systems Security Professional", link: "https://www.isc2.org/certifications/cissp", provider: "isc2" },
      { label: "SANS SEC549 — Enterprise Cloud Security Architecture", link: "https://www.sans.org/cyber-security-courses/enterprise-cloud-security-architecture/", provider: "sans" },
    ],
    labs: [
      { label: "Wiz Research — Cloud attack techniques and CVEs", link: "https://www.wiz.io/blog/research", provider: "wiz" },
      { label: "AWS Security Workshop Catalog", link: "https://catalog.workshops.aws/", provider: "aws" },
      { label: "SANS Cloud Security Curriculum", link: "https://www.sans.org/cloud-security/", provider: "sans" },
      { label: "BishopFox Cloud Security Research", link: "https://bishopfox.com/blog", provider: "github" },
      { label: "fwd:cloudsec Conference Papers", link: "https://fwdcloudsec.org/", provider: "github" },
    ],
  },
];

export const ACTIONS: Action[] = [
  {
    icon: "☁️",
    title: "Build Your Cloud Lab",
    color: "#a78bfa",
    border: "rgba(167,139,250,0.25)",
    glow: "rgba(167,139,250,0.08)",
    items: [
      { label: "flaws.cloud — free AWS challenge (best first lab)", link: "http://flaws.cloud/" },
      { label: "CloudGoat — deploy real-world vulnerable infra", link: "https://github.com/RhinoSecurityLabs/cloudgoat" },
      { label: "PwnedLabs — structured cloud security labs", link: "https://pwnedlabs.io/" },
      { label: "AWS Free Tier — hands-on with real services", link: "https://aws.amazon.com/free/" },
    ],
  },
  {
    icon: "📋",
    title: "Build Your Portfolio",
    color: "#8b5cf6",
    border: "rgba(139,92,246,0.25)",
    glow: "rgba(139,92,246,0.08)",
    items: [
      "Document flaws.cloud solutions as professional assessment reports",
      "GitHub: Prowler automation scripts and custom Config rules",
      "Write-ups of CloudGoat scenarios with attack paths and MITRE ATT&CK mappings",
      "Blog about a real misconfiguration you found and remediated",
    ],
  },
];
